---
title: "Pleural cfDNA Screening Array"
subtitle: "Compare EWAS results for self-reported vs. DNAm-score estimated variables"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: Paul Yousefi
output:
  html_document:
    css: docs/style.css
    toc: true
    highlight: tango
---

```{r setoptions, eval = TRUE, echo = FALSE}
knitr::opts_chunk$set(
comment = ">",
error = FALSE,
tidy = FALSE,
echo = FALSE, 
warning = FALSE, 
message = FALSE,
cache=FALSE)
```

```{r call_source, echo = F}
path <- "."
sourcecode <- grep("compare.r$", 
	list.files(path), value = T)
read_chunk(file.path(path, sourcecode))
```

```{r globals, results = 'hide', echo = F}
```

```{r load.data, echo = F}
```

```{r source-models, results = 'hide', echo = F}
```

# Background 

Noted in [ewas-summary.html](https://yousefi138.github.io/pleural-screening-array/ewas-summary.html) that self-reported age and smoking status did not show any significant associations with DNAm, but DNAm-estimated age and smoking status did. 

# Purpose

The purpose of this analysis report is to compare the EWAS results for self-report vs. DNAm-estimated variables to see if they're comparable. 


